### ISSUE TITLE
Setting a foreground blocks taps when scrolled

### ISSUE THREAD

**Issue by EyMaddis** [monterosalondon/react-native-parallax-scroll#23] opened 2018-04-13 11:04 UTC
### Issue details

When setting a foreground an empty view is created that acts as a placeholder and wrapper.
This has `position: 'absolute'` and the height according to the `parallaxHeight` property.
Because of this, the empty view is always in front of everything that renders as the content of the ScrollView.

```
          parallaxHeight={300}

          renderParallaxForeground={({ animatedValue, height }) => (
            <View style={{backgroundColor: 'red', width: '100%', height, opacity: 0.5}} />
          )}
```
![image](https://user-images.githubusercontent.com/1409100/38731490-bac1eb2c-3f1a-11e8-97ff-22b76b2d460f.png)

slightly scrolled and selected with the React-Native inspector:
![image](https://user-images.githubusercontent.com/1409100/38731529-ec10e1ec-3f1a-11e8-9a5c-a207243668a3.png)

Everything below the box is not touchable, i.e. the "Alle Anzeigen" button

- react-native 0.55.0
- react-native-parallax-scroll 1.7.0

### Affected platforms 
- Both

PR incoming

**Comment by EyMaddis** [comment] 2018-04-13 11:14
While the PR #24  does not fix it per se, it allows displaying headers that are supposed go with the scroll offset.
In theory the size of the view must be animated, however this blocks `useNativeDriver` as it cannot animate height outside of the Javascript engine.

**Comment by z4o4z** [comment] 2018-04-14 07:47
@EyMaddis can I close this issue?

**Comment by EyMaddis** [comment] 2018-04-14 09:06
Well, technically it is not solved, but a workaround is feasible (at least for me).
I am fine with closing as long as you don‘t have an idea how to properly fix this.

**Comment by EyMaddis** [comment] 2018-04-18 20:56
Maybe this can be properly solved by applying the foreground translation to the placeholder view or container instead of only the foreground. Unfortunately, I do not have time at the moment to look into this.

**Comment by z4o4z** [comment] 2018-04-19 07:07
Hi @EyMaddis, I just tried to reproduce your problem and it looks like everything works fine. The foreground wrappers have poinerEvents="box-none" prop, which means that touches won't work for this views, but will work for children. I think this problem can be solved in the client side app. What do you think about it?

**Comment by EyMaddis** [comment] 2018-04-19 22:05
> I think this problem can be solved in the client side app

What do you mean? Client side meaning "by the user with renderPlaceholderView"?

The wrapper has `box-none`, but the empty view does not. Maybe the default placeholder view should also get this property.

**Comment by z4o4z** [comment] 2018-04-23 08:35
Yep
> What do you mean? Client side meaning "by the user with renderPlaceholderView"?

Will add this later. For now, I close this issue
>Maybe the default placeholder view should also get this property.

**Closed** 2018-04-23 08:35 UTC
